service: sign-up
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  graphql:
    handler: signUp.handler
    events:
      - http:
          path: signUp
          method: post
          cors: true