service: graphql-api
package:
  patterns:
    - '!**'
    - '!**.test.*'
  individually: true
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  region: eu-central-1
  stage: prod
  runtime: nodejs14.x
  timeout: 30
  lambdaHashingVersion: 20201221
  layers:
    - arn:aws:lambda:eu-central-1:477719599351:layer:libs:54
    - arn:aws:lambda:eu-central-1:477719599351:layer:nodeModules:47
functions:
  gateway:
    handler: handlers/gateway/index.handler
    package:
      patterns:
        - handlers/gateway/*
    events:
      - http:
          path: /gateway
          method: post
          cors:
            origin: https://mathstutor.ru
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  profiles:
    handler: handlers/profiles/index.handler
    package:
      patterns:
        - handlers/profiles/*
    events:
      - http:
          path: /profiles
          method: post
          cors: true
  appointment:
    handler: handlers/appointment/index.handler
    package:
      patterns:
        - handlers/appointment/*
    events:
      - http:
          path: /appointment
          method: post
          cors: true
  course:
    handler: handlers/course/index.handler
    package:
      patterns:
        - handlers/course/*
    events:
      - http:
          path: /course
          method: post
          cors: true
  lessons:
    handler: handlers/lessons/index.handler
    package:
      patterns:
        - handlers/lessons/*
    events:
      - http:
          path: /lessons
          method: post
          cors: true
  tests:
    handler: handlers/tests/index.handler
    package:
      patterns:
        - handlers/tests/*
    events:
      - http:
          path: /tests
          method: post
          cors: true
  results:
    handler: handlers/results/index.handler
    package:
      patterns:
        - handlers/results/*
    events:
      - http:
          path: /results
          method: post
          cors: true
  problems:
    handler: handlers/problems/index.handler
    package:
      patterns:
        - handlers/problems/*
    events:
      - http:
          path: /problems
          method: post
          cors: true