service: graphql-api
package:
  patterns:
    - '!**'
    - '!**.test.*'
  individually: true
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  timeout: 15
  lambdaHashingVersion: 20201221
  layers:
    - arn:aws:lambda:eu-central-1:477719599351:layer:libs:50
    - arn:aws:lambda:eu-central-1:477719599351:layer:nodeModules:46
functions:
  gateway:
    handler: handlers/gateway/index.handler
    package:
      patterns:
        - handlers/gateway/*
    events:
      - http:
          path: /gateway
          method: post
          cors:
            origin: https://localhost:9000
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  profile:
    handler: handlers/profiles/index.handler
    package:
      patterns:
        - handlers/profiles/*
    events:
      - http:
          path: /profiles
          method: post
          cors: true
  appointment:
    handler: handlers/appointment/index.handler
    package:
      patterns:
        - handlers/appointment/*
    events:
      - http:
          path: /appointment
          method: post
          cors: true
  course:
    handler: handlers/course/index.handler
    package:
      patterns:
        - handlers/course/*
    events:
      - http:
          path: /course
          method: post
          cors: true
  lesson:
    handler: handlers/lesson/index.handler
    package:
      patterns:
        - handlers/lesson/*
    events:
      - http:
          path: /lesson
          method: post
          cors: true
  test:
    handler: handlers/test/index.handler
    package:
      patterns:
        - handlers/test/*
    events:
      - http:
          path: /test
          method: post
          cors: true
  testResult:
    handler: handlers/results/index.handler
    package:
      patterns:
        - handlers/results/*
    events:
      - http:
          path: /results
          method: post
          cors: true
  problem:
    handler: handlers/problem/index.handler
    package:
      patterns:
        - handlers/problem/*
    events:
      - http:
          path: /problem
          method: post
          cors: true