subgraphs:
  profile:
    routing_url: https://api.mathstutor.ru/profiles
    schema:
      subgraph_url: https://api.mathstutor.ru/profiles
  appointment:
    routing_url: https://api.mathstutor.ru/appointment
    schema:
      subgraph_url: https://api.mathstutor.ru/appointment
  course:
    routing_url: https://api.mathstutor.ru/course
    schema:
      subgraph_url: https://api.mathstutor.ru/course
  lesson:
    routing_url: https://api.mathstutor.ru/lesson
    schema:
      subgraph_url: https://api.mathstutor.ru/lesson
  test:
    routing_url: https://api.mathstutor.ru/tests
    schema:
      subgraph_url: https://api.mathstutor.ru/tests
  testResult:
    routing_url: https://api.mathstutor.ru/results
    schema:
      subgraph_url: https://api.mathstutor.ru/results
  problem:
    routing_url: https://api.mathstutor.ru/problems
    schema:
      subgraph_url: https://api.mathstutor.ru/problems
