subgraphs:
  profiles:
    routing_url: https://api.mathstutor.ru/profiles
    schema:
      subgraph_url: https://api.mathstutor.ru/profiles
  appointment:
    routing_url: https://api.mathstutor.ru/appointment
    schema:
      subgraph_url: https://api.mathstutor.ru/appointment
  course:
    routing_url: https://api.mathstutor.ru/course
    schema:
      subgraph_url: https://api.mathstutor.ru/course
  lessons:
    routing_url: https://api.mathstutor.ru/lessons
    schema:
      subgraph_url: https://api.mathstutor.ru/lessons
  tests:
    routing_url: https://api.mathstutor.ru/tests
    schema:
      subgraph_url: https://api.mathstutor.ru/tests
  results:
    routing_url: https://api.mathstutor.ru/results
    schema:
      subgraph_url: https://api.mathstutor.ru/results
  problems:
    routing_url: https://api.mathstutor.ru/problems
    schema:
      subgraph_url: https://api.mathstutor.ru/problems
